apiVersion: apps/v1
kind: StatefulSet #in place of deployment it will be statefulset
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  replicas: 3
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        env:  
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: POSTRES_USER
            value: postgres
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql 
          #the volume path we need to map 
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 1Gi
