apiVersion: v1
kind: Service
metadata:
  
  labels:
    app: usermgmt-webapp
  name: frontendservice
  namespace: default
  
spec:
  

  ports:
  - nodePort: 30255
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: usermgmt-webapp
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
