apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: prod
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql 
    spec:
      containers:
      - name: myapp
        image: mysql:5.6 
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD #this mysql root password secret manager 
          valueFrom:
            secretKeyRef:
              name: my-db-secret #this is the name of the secret we defin
              key: dbpassword #this is the key inside the secret
        volumeMounts:
        - name: mysql-sc
          mountPath: /var/lib/mysql #this is the path inside the container where the volume will be mounted
        - name: user-data
          mountPath: /docker-entrypoint-initdb.d #this is the path inside the container where the init script will be mounted
      nodeName: ip-172-31-93-198 #kindly modify the name name before you deploy
      volumes:
      - name: mysql-sc #line number 26 which the path of your contianer volume
      #this path is mapped to your pvc 
        persistentVolumeClaim:
          claimName: task-pv-claim #this is the name of the pvc we defined
      - name: user-data
        configMap:
          name: user-management-config #this is the name of the configmap we defined
          