apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
  namespace: prod
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  storageClassName: gopal
  accessModes:
    - ReadWriteOnce
#if the storage size and the access mode match it will dynamically attach with a pv